DB/web_odevii/Areas/AdminArea/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web_odevii.DataBase;
using web_odevii.Models;

namespace web_odevii.Areas.AdminArea.Controllers
{
    public class AdminHomeController : Controller
    {
        HalisahaContext db = new HalisahaContext();
        // GET AdminArea/AdminHome
        public ActionResult Index()
        {
            return View();
        }

        #region Kullanicilar İşlemler
   
        #region Kullanicilar()
        public ActionResult Kullanicilar()
        {
            var item = db.Kullanicilar.ToList();
            return View(item);
        }
        #endregion

        [HttpPost]
        #region Kullanicilar(Kullanici kullanici)

        public ActionResult Kullanicilar(Kullanici kullanici)
        {
            return View();
        }

        #endregion

        #region KullaniciEkle()

        public ActionResult KullaniciEkle()
        {
            return View();
        }

        #endregion

        [HttpPost]
        #region KullaniciEkle(Kullanici kullanici) formdan gelen bilgiler veri tabanına kaydediliyor

        public ActionResult KullaniciEkle(Kullanici kullanici)
        {
            Kullanici k = new Kullanici();
            k.KullaniciAdi = kullanici.KullaniciAdi;
            k.KullaniciSoyadi = kullanici.KullaniciSoyadi;
            k.KullaniciEmail = kullanici.KullaniciEmail;
            k.KullaniciParola = kullanici.KullaniciParola;
            k.KullaniciTelefonNo = kullanici.KullaniciTelefonNo;
            k.KullaniciYetki = kullanici.KullaniciYetki;

            db.Kullanicilar.Add(k);
            db.SaveChanges();
            return RedirectToAction("Kullanicilar");

        }

        #endregion


        #region KullaniciDuzenle(int id) gelen id ye gore kullanıcıyı duzenleme sayfası

        public ActionResult KullaniciDuzenle(int id)
        {
            Kullanici kullaniciDuzenle = db.Kullanicilar.FirstOrDefault(x => x.KullaniciID == id);

            return View(kullaniciDuzenle);
        }

        #endregion

        [HttpPost]
        #region KullaniciDuzenle(Kullanici kullanici) formdan gelen bilgiler Duzenlenip veri tabanına kaydediliyor

        public ActionResult KullaniciDuzenle(Kullanici kullanici)
        {

            Kullanici k = db.Kullanicilar.First(x => x.KullaniciID == kullanici.KullaniciID);

            k.KullaniciAdi = kullanici.KullaniciAdi;
            k.KullaniciSoyadi = kullanici.KullaniciSoyadi;
            k.KullaniciEmail = kullanici.KullaniciEmail;
            k.KullaniciParola = kullanici.KullaniciParola;
            k.KullaniciTelefonNo = kullanici.KullaniciTelefonNo;
            k.KullaniciYetki = kullanici.KullaniciYetki;

            db.SaveChanges();

            return RedirectToAction("Kullanicilar");

        }

        #endregion


        #region KullaniciSil(int id)

        public ActionResult KullaniciSil(int id)
        {
            Kullanici kullaniciSilinecek = db.Kullanicilar.FirstOrDefault(x => x.KullaniciID == id);
            
            db.Kullanicilar.Remove(kullaniciSilinecek);

            db.SaveChanges();

            return RedirectToAction("Kullanicilar");
        }

        #endregion

        #endregion


        #region Halisahalar işlemler
        
        #region Halisahalar()
        // Halisahalar viewi
        public ActionResult Halisahalar()
        {
            var veriler = db.Halisahalar.ToList();
            return View(veriler);
        }

        #endregion


        #region Halisahaekle()

        //burasının asagıdaki action resulttan farkı 
        //burası formun oldugu sayfa duz bir view
        //post methoduyla aynı isimdeki aşağıdaki method
        //ebu methodun viewindeki ekle butonuna tıklandığında bilgileri post 
        //ile o actionresult a gondereecek ve işlemler yapılacaktır.
        //burası ise duz bir sayfa
        public ActionResult HalisahaEkle()
        {
            return View();
        }

        #endregion
        //gelen bilgilerin post ile geleceğini soyluyoruz 
        //buraya bir şey yazmazsak default olarak [HttpGet] olarak get methodu ile bilgi aktarır
        [HttpPost]
        #region HalisahaEkle(Halisaha halisaha) 


        //post ile halisaha bilgileri paket halinde halisaha değişkeninin 
        //içine atanıyor burada Halisaha donus tipi normal bir classtan nesne 
        //alınıyor gibi dusunulmelidir.
        public ActionResult HalisahaEkle(Halisaha halisaha, HttpPostedFileBase HalisahaResimYol)
        {

            Kullanici query = db.Kullanicilar.First(x => x.KullaniciID == halisaha.HalisahaSahibi.KullaniciID);
            //paket halinde nesne parametre olarak geldi ve yeni h adında nesne oluşturduk
            Halisaha h = new Halisaha();

            //oluşturdugumuz yeni nesnenin icine postan gelen bilgileri atıyoruz
            h.HalisahaAdi = halisaha.HalisahaAdi;
            h.HalisahaAdres = halisaha.HalisahaAdres;
            h.HalisahaTelNo = halisaha.HalisahaTelNo;
            h.HalisahaUcret = halisaha.HalisahaUcret;
            h.HalisahaResimYol = HalisahaResimEkle(HalisahaResimYol);
            h.HalisahaSahibi = query;

            //posttan gelen bilgiler paket halinde k degislkeninin icine atandı
            //veritabanındaki halisahalar tablosuna yeni bir satır olarak ekledik
            db.Halisahalar.Add(h);
            //veri tabanındaki değişiklikleri kaydediyoruz
            db.SaveChanges();
            //yonlendirme olarak sayfayı halisahalar sayfasına yonlendiriyoruz 
            //return redirecttoroute...
            return RedirectToAction("Halisahalar");
        }



        private string HalisahaResimEkle(HttpPostedFileBase exampleInputFile)
        {
            Image image = Image.FromStream(exampleInputFile.InputStream);
            Bitmap bimage = new Bitmap(image, new Size { Width = 900, Height = 400 });
            string uzanti = System.IO.Path.GetExtension(exampleInputFile.FileName);
            string isim = Guid.NewGuid().ToString().Replace("-", "");
            string yol = "/Areas/AdminArea/AdminContent/images" + isim + uzanti;
            bimage.Save(Server.MapPath(yol));
            return yol;
        }
        #endregion

        #region HalisahaDüzenle()

        public ActionResult HalisahaDuzenle(int id)
        {
            Halisaha halisahaDuzenle = db.Halisahalar.FirstOrDefault(x => x.HalisahaID == id);
            ViewBag.kullanicilar = db.Kullanicilar.ToList();
            return View(halisahaDuzenle);
        }

        #endregion

        #region HalisahaDuzenle 
        [HttpPost]
        public ActionResult HalisahaDuzenle(Halisaha halisaha, HttpPostedFileBase HalisahaResimYol)
        {
          
            Halisaha h = db.Halisahalar.FirstOrDefault(x => x.HalisahaID == halisaha.HalisahaID);

            h.HalisahaAdi = halisaha.HalisahaAdi;
            if(halisaha.HalisahaAdres != "")
            h.HalisahaAdres = halisaha.HalisahaAdres;
            h.HalisahaTelNo = halisaha.HalisahaTelNo;
            h.HalisahaUcret = halisaha.HalisahaUcret;
            h.HalisahaResimYol = HalisahaResimEkle(HalisahaResimYol);
            db.SaveChanges();

            return RedirectToAction("Halisahalar");
        }

        #endregion

        #region HalisahaSil()
          [HttpGet]
        public ActionResult HalisahaSil(int id)
        {
            
            Halisaha halisahaSilinecek = db.Halisahalar.FirstOrDefault(x => x.HalisahaID == id);

            db.Halisahalar.Remove(halisahaSilinecek);

            db.SaveChanges();

            return RedirectToAction("Halisahalar");
        }




        #endregion

#endregion

        // Randevular viewi
        public ActionResult Randevular()
        {
            return View();
        }

       

    }

    
}

DB/web_odevii/Areas/AdminArea/Views/AdminHome/HalisahaDuzenle.cshtml
@{
    ViewBag.Title = "HalisahaDuzenle";
}
@using web_odevii.Models
@model Halisaha

<br /><br /><br /><br /><br /><br /><br />
<div>

    @using (Html.BeginForm("HalisahaDuzenle", "AdminHome", FormMethod.Post, htmlAttributes: new { id = "", @class = "was-validated", enctype = "multipart/form-data" }))
    {

        @Html.HiddenFor(x => x.HalisahaID)



        <div class="container">

            <!--
                       İSİM İNPUTU
              -->


            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-text-input" class="col-2 col-form-label">İsim</label>
                        <div class="col-10">
                            <input class="form-control" value="@Model.HalisahaAdi" name="HalisahaAdi" type="text" placeholder="Halisaha ismi giriniz..." id="example-text-input">
                        </div>
                    </div>
                </div>
            </div>

            <!--
                               TEXT AREA ADRES İNPUTU
            -->
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-text-input" class="col-2 col-form-label">Adres</label>
                        <div class="col-10">
                            <textarea name="HalisahaAdres" value="@Model.HalisahaAdres" class="form-control" placeholder="Halisaha Adresi Giriniz..." id="exampleTextarea" rows="3"></textarea>
                        </div>
                    </div>
                </div>
            </div>

            <div />

            <!--
                                     İSİM İNPUTU
             -->


            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-password-input" class="col-2 col-form-label">Telefon</label>
                        <div class="col-10">
                            <input class="form-control" value="@Model.HalisahaTelNo" name="HalisahaTelNo" type="text" placeholder="Halisaha Telefon No giriniz..." id="example-password-input">
                        </div>
                    </div>

                </div>

            </div>

 
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-text-input" class="col-2 col-form-label">Sahibi</label>
                        <div class="col-10">
                            <input class="form-control" value="@Model.HalisahaSahibi.KullaniciID" name="HalisahaSahibi.KullaniciID" type="text" placeholder="Halisaha Sahibi giriniz..." id="example-text-input">
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-tel-input" class="col-2 col-form-label">Ucret</label>
                        <div class="col-10">
                            <input class="form-control" value="@Model.HalisahaUcret" name="HalisahaUcret" type="tel" placeholder="Halisaha Ücreti giriniz..." id="example-tel-input">
                        </div>
                    </div>

                </div>

            </div>


            <div class="row">
                <div class="col-lg-6" align="right">

                    <label class="custom-file">
                        <input type="file" name="HalisahaResimYol" value="@Model.HalisahaResimYol" id="file" class="custom-file-input" required>
                        <span class="custom-file-control">
                            Bir Dosya seçiniz
                        </span>
                    </label>

                </div>
            </div>

            <br />

            <div class="row">
                <div class="col-md-6" align="right">
                    <button style="width:40%;" type="submit" class="btn btn-outline-success btn-lg">   Kayıt Et</button>
                </div>
            </div>
        </div>








    }

    
</div>

DB/web_odevii/Areas/AdminArea/Views/AdminHome/HalisahaEkle.cshtml
@{
    ViewBag.Title = "HalisahaEkle";
}

<br /><br /><br /><br /><br /><br /><br />
<div>
    
    @using (Html.BeginForm("HalisahaEkle", "AdminHome", FormMethod.Post, htmlAttributes: new { id = "", @class = "was-validated", enctype = "multipart/form-data" }))
    {
        <div class="container">

            <!--
                       İSİM İNPUTU
              -->


            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-text-input" class="col-2 col-form-label">İsim</label>
                        <div class="col-10">
                            <input class="form-control" name="HalisahaAdi" type="text" placeholder="Halisaha ismi giriniz..." id="example-text-input">
                        </div>
                    </div>
                </div>
            </div>
        
        <!--
                           TEXT AREA ADRES İNPUTU    
        -->
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-text-input" class="col-2 col-form-label">Adres</label>
                        <div class="col-10">      
                                <textarea name="HalisahaAdres" class="form-control" placeholder="Halisaha Adresi Giriniz..." id="exampleTextarea" rows="3"></textarea>
                        </div>
                    </div>
                </div>
            </div>

            <div/>

            <!--
                                     İSİM İNPUTU
             -->


            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-password-input" class="col-2 col-form-label">Telefon</label>
                        <div class="col-10">
                            <input class="form-control" name="HalisahaTelNo" type="text" placeholder="Halisaha Telefon No giriniz..." id="example-password-input">
                        </div>
                    </div>

                </div>

            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-text-input" class="col-2 col-form-label">Sahibi</label>
                        <div class="col-10">
                            <input class="form-control" name="HalisahaSahibi.KullaniciID" type="text" placeholder="Halisaha Sahibi giriniz..." id="example-text-input">
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-tel-input" class="col-2 col-form-label">Ucret</label>
                        <div class="col-10">
                            <input class="form-control" name="HalisahaUcret" type="tel" placeholder="Halisaha Ücreti giriniz..." id="example-tel-input">
                        </div>
                    </div>

                </div>

            </div>


            <div class="row">
                <div class="col-lg-6" align="right">
                    <label class="custom-file">
                        <input type="file" name="HalisahaResimYol" id="file" class="custom-file-input" required>
                        <span class="custom-file-control">
                            Bir Dosya seçiniz
                        </span>
                    </label>

                </div>

                </div>
            
            <br/>

            <div class="row">
                <div class="col-md-6" align="right">
                    <button style="width:40%;" type="submit" class="btn btn-outline-success btn-lg">   Kayıt Et</button>

                </div>

            </div>
            </div>

     }

        </div>

DB/web_odevii/Areas/AdminArea/Views/AdminHome/Halisahalar.cshtml
@{
    ViewBag.Title = "Halisahalar";
}

@using web_odevii.Models
@model IEnumerable<Halisaha>

<br/><br /><br /><br /><br /><br /><br />
<a style="text-decoration:none;" href="@Url.Action("HalisahaEkle","AdminHome")">
    <button type="button" class="btn btn-success btn-block">Yeni Halisaha Ekle</button>
</a>

<br />

<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Data Table Example
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr class="table-success">
                        <th scope="col">ID</th>
                        <th scope="col">Adı</th>
                        <th scope="col">Adres</th>
                        <th scope="col">İşletmeci Id</th>
                        <th scope="col">Telefon</th>
                        <th scope="col">Ucret</th>

                        <th>Sil</th>
                        <th>Düzenle</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr class="table-success">
                        <th scope="col">ID</th>
                        <th scope="col">Adı</th>
                        <th scope="col">Adres</th>
                        <th scope="col">İşletmeci Id</th>
                        <th scope="col">Telefon</th>
                        <th scope="col">Ucret</th>

                        <th>Sil</th>
                        <th>Düzenle</th>
                    </tr>
                </tfoot>



                @foreach (var item in Model)
                {
                    <tr class="table-secondary">
                        <th>@item.HalisahaID</th>

                        @if (item.HalisahaAdi.Length > 30)
                        {
                            <td>@item.HalisahaAdi.Substring(0, 28) ...</td>
                        }
                        else
                        {
                            <td>@item.HalisahaAdi</td>
                        }
                        @if (item.HalisahaAdres.Length > 30)
                        {
                            <td>@item.HalisahaAdres.Substring(0,28) ...</td>
                        }
                        else
                        {
                            <td>@item.HalisahaAdres</td>
                        }
                       
                        <td>@item.HalisahaTelNo</td>
                        <td>@item.HalisahaUcret</td>
                        
                        <td>
                            <a href="@Url.Action("HalisahaSil", "AdminHome", new { id = item.HalisahaID })">
                                <button type="button" class="btn btn-outline-danger btn-sm">Sil</button>
                            </a>
                        </td>

                        <td>
                            <a href="@Url.Action("HalisahaDuzenle", "AdminHome", new { id = item.HalisahaID })">
                                <button type="button" class="btn btn-outline-primary btn-sm">Düzenle</button>
                            </a>
                        </td>

                    </tr>
                }
                
            </table>
        </div>
    </div>
</div>

DB/web_odevii/Areas/AdminArea/Views/AdminHome/KullaniciDuzenle.cshtml
@{
    ViewBag.Title = "KullaniciDuzenle";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";

}


@using web_odevii.Models
@model Kullanici
<br /><br /><br /><br /><br /><br /><br />
@using (Html.BeginForm("KullaniciDuzenle", "AdminHome", FormMethod.Post, htmlAttributes: new { id = "", @class = "was-validated", enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x=> x.KullaniciID)


    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label for="example-text-input" class="col-2 col-form-label">İsim</label>
                    <div class="col-10">
                        <input class="form-control" name="KullaniciAdi" type="text" value="@Model.KullaniciAdi" placeholder="İsim giriniz..." id="example-text-input">
                    </div>
                </div>

            </div>
        </div>


    </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-search-input" class="col-2 col-form-label">Soyisim</label>
                        <div class="col-10">
                            <input class="form-control" name="KullaniciSoyadi" type="search" value="@Model.KullaniciSoyadi" placeholder="Soyisim giriniz..." id="example-search-input">
                        </div>
                    </div>

                </div>
            </div>

        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">

                    <div class="form-group row">
                        <label for="example-email-input" class="col-2 col-form-label">E-mail</label>
                        <div class="col-10">
                            <input class="form-control" type="email" name="KullaniciEmail" value="@Model.KullaniciEmail" placeholder="E-mail Adresi giriniz..." id="example-email-input">
                        </div>
                    </div>
                </div>

            </div>

        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-password-input" class="col-2 col-form-label">Parola</label>
                        <div class="col-10">
                            <input class="form-control" name="KullaniciParola" type="password" placeholder="Parola giriniz..." id="example-password-input">
                        </div>
                    </div>

                </div>

            </div>

        </div>


        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-tel-input" class="col-2 col-form-label">Telefon</label>
                        <div class="col-10">
                            <input class="form-control" name="KullaniciTelefonNo" type="tel" value="@Model.KullaniciTelefonNo" placeholder="Telefon giriniz..." id="example-tel-input">
                        </div>
                    </div>

                </div>

            </div>

        </div>


        <div class="container">
            <div class="row">
                <div class="col-md-6" align="right">
                    <select style="width:40%;" name="KullaniciYetki" class="custom-select d-block my-3" required>
                        Yetki
                        <option value="">Lütfen Yetki Seçiniz</option>
                        <option value="admin">Admin</option>
                        <option value="halisaha sahibi">Halisaha Sahibi</option>
                        <option value="Kullanici">Kullanici</option>
                    </select>

                </div>




            </div>

        </div>





        <!--

             Dosya seçme işlemi için

            <label class="custom-file">
             <input type="file" id="file" class="custom-file-input" required>
             <span class="custom-file-control">
               Bir Dosya seçiniz
             </span>
         </label>

            -->
        <div class="container">
            <div class="row">
                <div class="col-md-6" align="right">
                    <button style="width:40%;" type="submit" class="btn btn-outline-success btn-lg">   Kayıt Et</button>

                </div>

            </div>

        </div>





}

DB/web_odevii/Areas/AdminArea/Views/AdminHome/KullaniciEkle.cshtml
@{
    ViewBag.Title = "KullaniciEkle";
}
<br /><br /><br /><br /><br /><br /><br />
<div >
    @using (Html.BeginForm("KullaniciEkle", "AdminHome", FormMethod.Post, htmlAttributes: new { id = "", @class = "was-validated", enctype = "multipart/form-data" }))
    {
       
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-text-input" class="col-2 col-form-label">İsim</label>
                        <div class="col-10">
                            <input class="form-control" name="KullaniciAdi" type="text" placeholder="İsim giriniz..."  id="example-text-input">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-search-input" class="col-2 col-form-label">Soyisim</label>
                        <div class="col-10">
                            <input class="form-control" name="KullaniciSoyadi" type="search"  placeholder="Soyisim giriniz..."   id="example-search-input">
                        </div>                                
                    </div>

                </div>
            </div>

        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">

                    <div class="form-group row">
                        <label for="example-email-input" class="col-2 col-form-label">E-mail</label>
                        <div class="col-10">
                            <input class="form-control" type="email" name="KullaniciEmail"  placeholder="E-mail Adresi giriniz..."   id="example-email-input">
                        </div>
                    </div>
                </div>

            </div>

        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-password-input" class="col-2 col-form-label">Parola</label>
                        <div class="col-10">
                            <input class="form-control" name="KullaniciParola" type="password"  placeholder="Parola giriniz..."    id="example-password-input">
                        </div>
                    </div>
                   
                </div>

            </div>

        </div>


        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="example-tel-input" class="col-2 col-form-label">Telefon</label>
                        <div class="col-10">
                            <input class="form-control" name="KullaniciTelefonNo" type="tel"  placeholder="Telefon giriniz..."    id="example-tel-input">
                        </div>
                    </div>

                </div>

            </div>

        </div>


        <div class="container">
            <div class="row">
                <div class="col-md-6" align="right">
                    <select style="width:40%;" name="KullaniciYetki" class="custom-select d-block my-3" required>
                        Yetki
                        <option value="">Lütfen Yetki Seçiniz</option>
                        <option value="Admin">Admin</option>
                        <option value="Halisaha Sahibi">Halisaha Sahibi</option>
                        <option value="Kullanici">Kullanici</option>
                    </select>

                </div>




            </div>

        </div>





        <!--

             Dosya seçme işlemi için

            <label class="custom-file">
             <input type="file" id="file" class="custom-file-input" required>
             <span class="custom-file-control">
               Bir Dosya seçiniz
             </span>
         </label>

            -->
        <div class="container">
            <div class="row">
                <div class="col-md-6" align="right">
                    <button style="width:40%;" type="submit" class="btn btn-outline-success btn-lg">   Kayıt Et</button>
                </div>

            </div>

        </div>


     }

</div>

DB/web_odevii/Areas/AdminArea/Views/AdminHome/Kullanicilar.cshtml
@{
    ViewBag.Title = "Kullanicilar";
}


@using web_odevii.Models
@model IEnumerable<Kullanici>
@{
    ViewBag.Title = "Kullanicilar";
}
<br /><br /><br /><br /><br /><br /><br />
<a style="text-decoration:none;" href="@Url.Action("KullaniciEkle","AdminHome")">
    <button type="button" class="btn btn-success btn-block">Yeni Kullanıcı Ekle</button>
</a>

<br />


<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Data Table Example
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr class="table-success">
                        <th scope="col">ID</th>
                        <th scope="col">Adı</th>
                        <th scope="col">Soyadı</th>
                        <th scope="col">E-mail</th>
                        <th scope="col">Parola</th> 
                        <th scope="col">Telefon</th>
                        <th scope="col">yetkisi</th>

                        <th>Sil</th>
                        <th>Düzenle</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr class="table-success">
                        <th scope="col">ID</th>
                        <th scope="col">Adı</th>
                        <th scope="col">Soyadı</th>
                        <th scope="col">E-mail</th>
                        <th scope="col">Parola</th>
                        <th scope="col">Telefon</th>
                        <th scope="col">yetkisi</th>

                        <th>Sil</th>
                        <th>Düzenle</th>
                    </tr>
                </tfoot>

               

                   @foreach (var item in Model)
                   {
                    <tr class="table-secondary">
                        <th scope="row">@item.KullaniciID</th>
                        <td>@item.KullaniciAdi</td>
                        <td>@item.KullaniciSoyadi</td>
                        <td>@item.KullaniciEmail</td>
                        <td>@item.KullaniciParola</td>
                        <td>@item.KullaniciTelefonNo</td>
                        <td>@item.KullaniciYetki</td>

                        <td>
                            <a href="@Url.Action("KullaniciSil", "AdminHome", new { id = item.KullaniciID })">
                                <button type="button" class="btn btn-outline-danger btn-sm">Sil</button>
                            </a>
                        </td>

                        <td>
                            <a href="@Url.Action("KullaniciDuzenle", "AdminHome", new { id = item.KullaniciID })">
                                <button type="button" class="btn btn-outline-primary btn-sm">Düzenle</button>
                            </a>
                        </td>

                    </tr>
                    }
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>